// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/skylens.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectionSource int32

const (
	DetectionSource_SOURCE_UNKNOWN         DetectionSource = 0
	DetectionSource_SOURCE_WIFI_BEACON     DetectionSource = 1 // 802.11 Beacon with RemoteID IE
	DetectionSource_SOURCE_WIFI_NAN        DetectionSource = 2 // WiFi Neighbor Awareness Networking
	DetectionSource_SOURCE_WIFI_PROBE_RESP DetectionSource = 3 // Probe Response
	DetectionSource_SOURCE_BLUETOOTH_4     DetectionSource = 4 // BT4 Legacy Advertising
	DetectionSource_SOURCE_BLUETOOTH_5     DetectionSource = 5 // BT5 Long Range
	DetectionSource_SOURCE_DJI_OCUSYNC     DetectionSource = 6 // DJI proprietary (OcuSync/DroneID)
	DetectionSource_SOURCE_ADS_B           DetectionSource = 7 // Future: ADS-B for larger drones
	DetectionSource_SOURCE_TSHARK_REMOTEID DetectionSource = 8 // OpenDroneID via tshark dissector
	DetectionSource_SOURCE_TSHARK_SSID     DetectionSource = 9 // Drone SSID match via tshark
)

// Enum value maps for DetectionSource.
var (
	DetectionSource_name = map[int32]string{
		0: "SOURCE_UNKNOWN",
		1: "SOURCE_WIFI_BEACON",
		2: "SOURCE_WIFI_NAN",
		3: "SOURCE_WIFI_PROBE_RESP",
		4: "SOURCE_BLUETOOTH_4",
		5: "SOURCE_BLUETOOTH_5",
		6: "SOURCE_DJI_OCUSYNC",
		7: "SOURCE_ADS_B",
		8: "SOURCE_TSHARK_REMOTEID",
		9: "SOURCE_TSHARK_SSID",
	}
	DetectionSource_value = map[string]int32{
		"SOURCE_UNKNOWN":         0,
		"SOURCE_WIFI_BEACON":     1,
		"SOURCE_WIFI_NAN":        2,
		"SOURCE_WIFI_PROBE_RESP": 3,
		"SOURCE_BLUETOOTH_4":     4,
		"SOURCE_BLUETOOTH_5":     5,
		"SOURCE_DJI_OCUSYNC":     6,
		"SOURCE_ADS_B":           7,
		"SOURCE_TSHARK_REMOTEID": 8,
		"SOURCE_TSHARK_SSID":     9,
	}
)

func (x DetectionSource) Enum() *DetectionSource {
	p := new(DetectionSource)
	*p = x
	return p
}

func (x DetectionSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectionSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_skylens_proto_enumTypes[0].Descriptor()
}

func (DetectionSource) Type() protoreflect.EnumType {
	return &file_proto_skylens_proto_enumTypes[0]
}

func (x DetectionSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetectionSource.Descriptor instead.
func (DetectionSource) EnumDescriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{0}
}

type HeightReference int32

const (
	HeightReference_HEIGHT_REF_UNKNOWN HeightReference = 0
	HeightReference_HEIGHT_REF_TAKEOFF HeightReference = 1 // Above takeoff point
	HeightReference_HEIGHT_REF_GROUND  HeightReference = 2 // Above ground level (AGL)
)

// Enum value maps for HeightReference.
var (
	HeightReference_name = map[int32]string{
		0: "HEIGHT_REF_UNKNOWN",
		1: "HEIGHT_REF_TAKEOFF",
		2: "HEIGHT_REF_GROUND",
	}
	HeightReference_value = map[string]int32{
		"HEIGHT_REF_UNKNOWN": 0,
		"HEIGHT_REF_TAKEOFF": 1,
		"HEIGHT_REF_GROUND":  2,
	}
)

func (x HeightReference) Enum() *HeightReference {
	p := new(HeightReference)
	*p = x
	return p
}

func (x HeightReference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeightReference) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_skylens_proto_enumTypes[1].Descriptor()
}

func (HeightReference) Type() protoreflect.EnumType {
	return &file_proto_skylens_proto_enumTypes[1]
}

func (x HeightReference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeightReference.Descriptor instead.
func (HeightReference) EnumDescriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{1}
}

type OperatorLocationType int32

const (
	OperatorLocationType_OP_LOC_UNKNOWN   OperatorLocationType = 0
	OperatorLocationType_OP_LOC_TAKEOFF   OperatorLocationType = 1 // Takeoff location
	OperatorLocationType_OP_LOC_LIVE_GNSS OperatorLocationType = 2 // Live GPS from controller
	OperatorLocationType_OP_LOC_FIXED     OperatorLocationType = 3 // Pre-configured fixed location
)

// Enum value maps for OperatorLocationType.
var (
	OperatorLocationType_name = map[int32]string{
		0: "OP_LOC_UNKNOWN",
		1: "OP_LOC_TAKEOFF",
		2: "OP_LOC_LIVE_GNSS",
		3: "OP_LOC_FIXED",
	}
	OperatorLocationType_value = map[string]int32{
		"OP_LOC_UNKNOWN":   0,
		"OP_LOC_TAKEOFF":   1,
		"OP_LOC_LIVE_GNSS": 2,
		"OP_LOC_FIXED":     3,
	}
)

func (x OperatorLocationType) Enum() *OperatorLocationType {
	p := new(OperatorLocationType)
	*p = x
	return p
}

func (x OperatorLocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorLocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_skylens_proto_enumTypes[2].Descriptor()
}

func (OperatorLocationType) Type() protoreflect.EnumType {
	return &file_proto_skylens_proto_enumTypes[2]
}

func (x OperatorLocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorLocationType.Descriptor instead.
func (OperatorLocationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{2}
}

type UAVCategory int32

const (
	UAVCategory_UAV_CAT_UNKNOWN         UAVCategory = 0
	UAVCategory_UAV_CAT_UNDECLARED      UAVCategory = 1
	UAVCategory_UAV_CAT_AEROPLANE       UAVCategory = 2
	UAVCategory_UAV_CAT_HELICOPTER      UAVCategory = 3 // Including multirotor
	UAVCategory_UAV_CAT_GYROPLANE       UAVCategory = 4
	UAVCategory_UAV_CAT_HYBRID_LIFT     UAVCategory = 5 // VTOL fixed-wing
	UAVCategory_UAV_CAT_ORNITHOPTER     UAVCategory = 6
	UAVCategory_UAV_CAT_GLIDER          UAVCategory = 7
	UAVCategory_UAV_CAT_KITE            UAVCategory = 8
	UAVCategory_UAV_CAT_FREE_BALLOON    UAVCategory = 9
	UAVCategory_UAV_CAT_CAPTIVE_BALLOON UAVCategory = 10
	UAVCategory_UAV_CAT_AIRSHIP         UAVCategory = 11
	UAVCategory_UAV_CAT_FREE_FALL       UAVCategory = 12 // Parachute/unpowered
	UAVCategory_UAV_CAT_ROCKET          UAVCategory = 13
	UAVCategory_UAV_CAT_GROUND_OBSTACLE UAVCategory = 14
	UAVCategory_UAV_CAT_OTHER           UAVCategory = 15
)

// Enum value maps for UAVCategory.
var (
	UAVCategory_name = map[int32]string{
		0:  "UAV_CAT_UNKNOWN",
		1:  "UAV_CAT_UNDECLARED",
		2:  "UAV_CAT_AEROPLANE",
		3:  "UAV_CAT_HELICOPTER",
		4:  "UAV_CAT_GYROPLANE",
		5:  "UAV_CAT_HYBRID_LIFT",
		6:  "UAV_CAT_ORNITHOPTER",
		7:  "UAV_CAT_GLIDER",
		8:  "UAV_CAT_KITE",
		9:  "UAV_CAT_FREE_BALLOON",
		10: "UAV_CAT_CAPTIVE_BALLOON",
		11: "UAV_CAT_AIRSHIP",
		12: "UAV_CAT_FREE_FALL",
		13: "UAV_CAT_ROCKET",
		14: "UAV_CAT_GROUND_OBSTACLE",
		15: "UAV_CAT_OTHER",
	}
	UAVCategory_value = map[string]int32{
		"UAV_CAT_UNKNOWN":         0,
		"UAV_CAT_UNDECLARED":      1,
		"UAV_CAT_AEROPLANE":       2,
		"UAV_CAT_HELICOPTER":      3,
		"UAV_CAT_GYROPLANE":       4,
		"UAV_CAT_HYBRID_LIFT":     5,
		"UAV_CAT_ORNITHOPTER":     6,
		"UAV_CAT_GLIDER":          7,
		"UAV_CAT_KITE":            8,
		"UAV_CAT_FREE_BALLOON":    9,
		"UAV_CAT_CAPTIVE_BALLOON": 10,
		"UAV_CAT_AIRSHIP":         11,
		"UAV_CAT_FREE_FALL":       12,
		"UAV_CAT_ROCKET":          13,
		"UAV_CAT_GROUND_OBSTACLE": 14,
		"UAV_CAT_OTHER":           15,
	}
)

func (x UAVCategory) Enum() *UAVCategory {
	p := new(UAVCategory)
	*p = x
	return p
}

func (x UAVCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UAVCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_skylens_proto_enumTypes[3].Descriptor()
}

func (UAVCategory) Type() protoreflect.EnumType {
	return &file_proto_skylens_proto_enumTypes[3]
}

func (x UAVCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UAVCategory.Descriptor instead.
func (UAVCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{3}
}

type OperationalStatus int32

const (
	OperationalStatus_OP_STATUS_UNKNOWN           OperationalStatus = 0
	OperationalStatus_OP_STATUS_UNDECLARED        OperationalStatus = 1
	OperationalStatus_OP_STATUS_GROUND            OperationalStatus = 2
	OperationalStatus_OP_STATUS_AIRBORNE          OperationalStatus = 3
	OperationalStatus_OP_STATUS_EMERGENCY         OperationalStatus = 4
	OperationalStatus_OP_STATUS_REMOTE_ID_FAILURE OperationalStatus = 5
)

// Enum value maps for OperationalStatus.
var (
	OperationalStatus_name = map[int32]string{
		0: "OP_STATUS_UNKNOWN",
		1: "OP_STATUS_UNDECLARED",
		2: "OP_STATUS_GROUND",
		3: "OP_STATUS_AIRBORNE",
		4: "OP_STATUS_EMERGENCY",
		5: "OP_STATUS_REMOTE_ID_FAILURE",
	}
	OperationalStatus_value = map[string]int32{
		"OP_STATUS_UNKNOWN":           0,
		"OP_STATUS_UNDECLARED":        1,
		"OP_STATUS_GROUND":            2,
		"OP_STATUS_AIRBORNE":          3,
		"OP_STATUS_EMERGENCY":         4,
		"OP_STATUS_REMOTE_ID_FAILURE": 5,
	}
)

func (x OperationalStatus) Enum() *OperationalStatus {
	p := new(OperationalStatus)
	*p = x
	return p
}

func (x OperationalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_skylens_proto_enumTypes[4].Descriptor()
}

func (OperationalStatus) Type() protoreflect.EnumType {
	return &file_proto_skylens_proto_enumTypes[4]
}

func (x OperationalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationalStatus.Descriptor instead.
func (OperationalStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{4}
}

type AlertPriority int32

const (
	AlertPriority_ALERT_INFO     AlertPriority = 0
	AlertPriority_ALERT_WARNING  AlertPriority = 1
	AlertPriority_ALERT_HIGH     AlertPriority = 2
	AlertPriority_ALERT_CRITICAL AlertPriority = 3
)

// Enum value maps for AlertPriority.
var (
	AlertPriority_name = map[int32]string{
		0: "ALERT_INFO",
		1: "ALERT_WARNING",
		2: "ALERT_HIGH",
		3: "ALERT_CRITICAL",
	}
	AlertPriority_value = map[string]int32{
		"ALERT_INFO":     0,
		"ALERT_WARNING":  1,
		"ALERT_HIGH":     2,
		"ALERT_CRITICAL": 3,
	}
)

func (x AlertPriority) Enum() *AlertPriority {
	p := new(AlertPriority)
	*p = x
	return p
}

func (x AlertPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_skylens_proto_enumTypes[5].Descriptor()
}

func (AlertPriority) Type() protoreflect.EnumType {
	return &file_proto_skylens_proto_enumTypes[5]
}

func (x AlertPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertPriority.Descriptor instead.
func (AlertPriority) EnumDescriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{5}
}

type AlertType int32

const (
	AlertType_ALERT_TYPE_UNKNOWN        AlertType = 0
	AlertType_ALERT_TYPE_NEW_DRONE      AlertType = 1
	AlertType_ALERT_TYPE_DRONE_LOST     AlertType = 2
	AlertType_ALERT_TYPE_SPOOF_DETECTED AlertType = 3
	AlertType_ALERT_TYPE_ZONE_VIOLATION AlertType = 4
	AlertType_ALERT_TYPE_LOW_TRUST      AlertType = 5
	AlertType_ALERT_TYPE_TAP_OFFLINE    AlertType = 6
	AlertType_ALERT_TYPE_TAP_ONLINE     AlertType = 7
	AlertType_ALERT_TYPE_SYSTEM_ERROR   AlertType = 8
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNKNOWN",
		1: "ALERT_TYPE_NEW_DRONE",
		2: "ALERT_TYPE_DRONE_LOST",
		3: "ALERT_TYPE_SPOOF_DETECTED",
		4: "ALERT_TYPE_ZONE_VIOLATION",
		5: "ALERT_TYPE_LOW_TRUST",
		6: "ALERT_TYPE_TAP_OFFLINE",
		7: "ALERT_TYPE_TAP_ONLINE",
		8: "ALERT_TYPE_SYSTEM_ERROR",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNKNOWN":        0,
		"ALERT_TYPE_NEW_DRONE":      1,
		"ALERT_TYPE_DRONE_LOST":     2,
		"ALERT_TYPE_SPOOF_DETECTED": 3,
		"ALERT_TYPE_ZONE_VIOLATION": 4,
		"ALERT_TYPE_LOW_TRUST":      5,
		"ALERT_TYPE_TAP_OFFLINE":    6,
		"ALERT_TYPE_TAP_ONLINE":     7,
		"ALERT_TYPE_SYSTEM_ERROR":   8,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_skylens_proto_enumTypes[6].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_proto_skylens_proto_enumTypes[6]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{6}
}

type Detection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Source identification ──
	TapId       string `protobuf:"bytes,1,opt,name=tap_id,json=tapId,proto3" json:"tap_id,omitempty"`                    // UUID of the tap that detected this
	TimestampNs int64  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Unix nanoseconds (for sub-ms precision)
	// ── Drone identification ──
	MacAddress   string `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`       // WiFi MAC (format: "AA:BB:CC:DD:EE:FF")
	Identifier   string `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"`                         // Primary ID (serial or generated)
	SerialNumber string `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"` // RemoteID serial (if available)
	Registration string `protobuf:"bytes,6,opt,name=registration,proto3" json:"registration,omitempty"`                     // CAA/FAA registration ID
	SessionId    string `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // RemoteID session ID
	UtmId        string `protobuf:"bytes,8,opt,name=utm_id,json=utmId,proto3" json:"utm_id,omitempty"`                      // UTM assigned ID
	// ── Position ──
	Latitude         float64         `protobuf:"fixed64,10,opt,name=latitude,proto3" json:"latitude,omitempty"`                                                                  // WGS84 degrees
	Longitude        float64         `protobuf:"fixed64,11,opt,name=longitude,proto3" json:"longitude,omitempty"`                                                                // WGS84 degrees
	AltitudeGeodetic float32         `protobuf:"fixed32,12,opt,name=altitude_geodetic,json=altitudeGeodetic,proto3" json:"altitude_geodetic,omitempty"`                          // Meters above WGS84 ellipsoid
	AltitudePressure float32         `protobuf:"fixed32,13,opt,name=altitude_pressure,json=altitudePressure,proto3" json:"altitude_pressure,omitempty"`                          // Meters above MSL (barometric)
	HeightAgl        float32         `protobuf:"fixed32,14,opt,name=height_agl,json=heightAgl,proto3" json:"height_agl,omitempty"`                                               // Meters above ground/takeoff
	HeightReference  HeightReference `protobuf:"varint,15,opt,name=height_reference,json=heightReference,proto3,enum=skylens.HeightReference" json:"height_reference,omitempty"` // What height is relative to
	// ── Movement ──
	Speed          float32 `protobuf:"fixed32,20,opt,name=speed,proto3" json:"speed,omitempty"`                                         // Ground speed m/s
	VerticalSpeed  float32 `protobuf:"fixed32,21,opt,name=vertical_speed,json=verticalSpeed,proto3" json:"vertical_speed,omitempty"`    // Climb/descent m/s (positive = up)
	Heading        float32 `protobuf:"fixed32,22,opt,name=heading,proto3" json:"heading,omitempty"`                                     // Track/ground course degrees (0-359)
	TrackDirection float32 `protobuf:"fixed32,23,opt,name=track_direction,json=trackDirection,proto3" json:"track_direction,omitempty"` // Direction of travel
	// ── Operator position ──
	OperatorLatitude     float64              `protobuf:"fixed64,30,opt,name=operator_latitude,json=operatorLatitude,proto3" json:"operator_latitude,omitempty"`
	OperatorLongitude    float64              `protobuf:"fixed64,31,opt,name=operator_longitude,json=operatorLongitude,proto3" json:"operator_longitude,omitempty"`
	OperatorAltitude     float32              `protobuf:"fixed32,32,opt,name=operator_altitude,json=operatorAltitude,proto3" json:"operator_altitude,omitempty"`
	OperatorLocationType OperatorLocationType `protobuf:"varint,33,opt,name=operator_location_type,json=operatorLocationType,proto3,enum=skylens.OperatorLocationType" json:"operator_location_type,omitempty"`
	OperatorId           string               `protobuf:"bytes,34,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // Operator/pilot ID if broadcast
	// ── Signal characteristics ──
	Rssi             int32  `protobuf:"varint,40,opt,name=rssi,proto3" json:"rssi,omitempty"`                                                   // Signal strength dBm
	Channel          int32  `protobuf:"varint,41,opt,name=channel,proto3" json:"channel,omitempty"`                                             // WiFi channel
	FrequencyMhz     int32  `protobuf:"varint,42,opt,name=frequency_mhz,json=frequencyMhz,proto3" json:"frequency_mhz,omitempty"`               // Exact frequency if known
	Ssid             string `protobuf:"bytes,43,opt,name=ssid,proto3" json:"ssid,omitempty"`                                                    // WiFi SSID (from beacon/probe)
	BeaconIntervalTu uint32 `protobuf:"varint,44,opt,name=beacon_interval_tu,json=beaconIntervalTu,proto3" json:"beacon_interval_tu,omitempty"` // Beacon interval in Time Units (1 TU = 1.024ms)
	// ── Detection metadata ──
	Source            DetectionSource   `protobuf:"varint,50,opt,name=source,proto3,enum=skylens.DetectionSource" json:"source,omitempty"`                          // How we detected this
	UavType           string            `protobuf:"bytes,51,opt,name=uav_type,json=uavType,proto3" json:"uav_type,omitempty"`                                       // RemoteID UA type string
	UavCategory       UAVCategory       `protobuf:"varint,52,opt,name=uav_category,json=uavCategory,proto3,enum=skylens.UAVCategory" json:"uav_category,omitempty"` // Categorization
	Designation       string            `protobuf:"bytes,53,opt,name=designation,proto3" json:"designation,omitempty"`                                              // Decoded model name (e.g., "DJI Mavic 3")
	Manufacturer      string            `protobuf:"bytes,54,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`                                            // Manufacturer name
	OperationalStatus OperationalStatus `protobuf:"varint,55,opt,name=operational_status,json=operationalStatus,proto3,enum=skylens.OperationalStatus" json:"operational_status,omitempty"`
	Confidence        float32           `protobuf:"fixed32,56,opt,name=confidence,proto3" json:"confidence,omitempty"`                        // Detection confidence (0.0 - 1.0)
	IsController      bool              `protobuf:"varint,58,opt,name=is_controller,json=isController,proto3" json:"is_controller,omitempty"` // True if remote controller, not drone
	CountryCode       string            `protobuf:"bytes,59,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`     // Country IE from beacon (e.g. "US", "CN") — firmware region
	// ── Raw data (optional, for debugging/analysis) ──
	RawFrame        []byte `protobuf:"bytes,60,opt,name=raw_frame,json=rawFrame,proto3" json:"raw_frame,omitempty"`                      // Full 802.11 frame
	RemoteidPayload []byte `protobuf:"bytes,61,opt,name=remoteid_payload,json=remoteidPayload,proto3" json:"remoteid_payload,omitempty"` // Just the RemoteID TLV data
	// ── Extended 802.11 fingerprint ──
	HtCapabilities uint32 `protobuf:"varint,70,opt,name=ht_capabilities,json=htCapabilities,proto3" json:"ht_capabilities,omitempty"` // HT Capability Info (802.11n) — device hardware fingerprint
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_proto_skylens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{0}
}

func (x *Detection) GetTapId() string {
	if x != nil {
		return x.TapId
	}
	return ""
}

func (x *Detection) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Detection) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Detection) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Detection) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Detection) GetRegistration() string {
	if x != nil {
		return x.Registration
	}
	return ""
}

func (x *Detection) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Detection) GetUtmId() string {
	if x != nil {
		return x.UtmId
	}
	return ""
}

func (x *Detection) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Detection) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Detection) GetAltitudeGeodetic() float32 {
	if x != nil {
		return x.AltitudeGeodetic
	}
	return 0
}

func (x *Detection) GetAltitudePressure() float32 {
	if x != nil {
		return x.AltitudePressure
	}
	return 0
}

func (x *Detection) GetHeightAgl() float32 {
	if x != nil {
		return x.HeightAgl
	}
	return 0
}

func (x *Detection) GetHeightReference() HeightReference {
	if x != nil {
		return x.HeightReference
	}
	return HeightReference_HEIGHT_REF_UNKNOWN
}

func (x *Detection) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Detection) GetVerticalSpeed() float32 {
	if x != nil {
		return x.VerticalSpeed
	}
	return 0
}

func (x *Detection) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *Detection) GetTrackDirection() float32 {
	if x != nil {
		return x.TrackDirection
	}
	return 0
}

func (x *Detection) GetOperatorLatitude() float64 {
	if x != nil {
		return x.OperatorLatitude
	}
	return 0
}

func (x *Detection) GetOperatorLongitude() float64 {
	if x != nil {
		return x.OperatorLongitude
	}
	return 0
}

func (x *Detection) GetOperatorAltitude() float32 {
	if x != nil {
		return x.OperatorAltitude
	}
	return 0
}

func (x *Detection) GetOperatorLocationType() OperatorLocationType {
	if x != nil {
		return x.OperatorLocationType
	}
	return OperatorLocationType_OP_LOC_UNKNOWN
}

func (x *Detection) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *Detection) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *Detection) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Detection) GetFrequencyMhz() int32 {
	if x != nil {
		return x.FrequencyMhz
	}
	return 0
}

func (x *Detection) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *Detection) GetBeaconIntervalTu() uint32 {
	if x != nil {
		return x.BeaconIntervalTu
	}
	return 0
}

func (x *Detection) GetSource() DetectionSource {
	if x != nil {
		return x.Source
	}
	return DetectionSource_SOURCE_UNKNOWN
}

func (x *Detection) GetUavType() string {
	if x != nil {
		return x.UavType
	}
	return ""
}

func (x *Detection) GetUavCategory() UAVCategory {
	if x != nil {
		return x.UavCategory
	}
	return UAVCategory_UAV_CAT_UNKNOWN
}

func (x *Detection) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

func (x *Detection) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Detection) GetOperationalStatus() OperationalStatus {
	if x != nil {
		return x.OperationalStatus
	}
	return OperationalStatus_OP_STATUS_UNKNOWN
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetIsController() bool {
	if x != nil {
		return x.IsController
	}
	return false
}

func (x *Detection) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Detection) GetRawFrame() []byte {
	if x != nil {
		return x.RawFrame
	}
	return nil
}

func (x *Detection) GetRemoteidPayload() []byte {
	if x != nil {
		return x.RemoteidPayload
	}
	return nil
}

func (x *Detection) GetHtCapabilities() uint32 {
	if x != nil {
		return x.HtCapabilities
	}
	return 0
}

type TapHeartbeat struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TapId       string                 `protobuf:"bytes,1,opt,name=tap_id,json=tapId,proto3" json:"tap_id,omitempty"`
	TapName     string                 `protobuf:"bytes,2,opt,name=tap_name,json=tapName,proto3" json:"tap_name,omitempty"`
	TimestampNs int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	// ── Tap location ──
	Latitude  float64 `protobuf:"fixed64,10,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,11,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude  float32 `protobuf:"fixed32,12,opt,name=altitude,proto3" json:"altitude,omitempty"`
	// ── Statistics ──
	Stats *TapStats `protobuf:"bytes,20,opt,name=stats,proto3" json:"stats,omitempty"`
	// ── System health ──
	CpuPercent         float32 `protobuf:"fixed32,30,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent      float32 `protobuf:"fixed32,31,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	TemperatureCelsius float32 `protobuf:"fixed32,32,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	WifiInterface      string  `protobuf:"bytes,33,opt,name=wifi_interface,json=wifiInterface,proto3" json:"wifi_interface,omitempty"`
	Version            string  `protobuf:"bytes,34,opt,name=version,proto3" json:"version,omitempty"`
	BleInterface       string  `protobuf:"bytes,35,opt,name=ble_interface,json=bleInterface,proto3" json:"ble_interface,omitempty"` // BLE adapter name (e.g. "hci0")
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TapHeartbeat) Reset() {
	*x = TapHeartbeat{}
	mi := &file_proto_skylens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapHeartbeat) ProtoMessage() {}

func (x *TapHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapHeartbeat.ProtoReflect.Descriptor instead.
func (*TapHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{1}
}

func (x *TapHeartbeat) GetTapId() string {
	if x != nil {
		return x.TapId
	}
	return ""
}

func (x *TapHeartbeat) GetTapName() string {
	if x != nil {
		return x.TapName
	}
	return ""
}

func (x *TapHeartbeat) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TapHeartbeat) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TapHeartbeat) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TapHeartbeat) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *TapHeartbeat) GetStats() *TapStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *TapHeartbeat) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *TapHeartbeat) GetMemoryPercent() float32 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *TapHeartbeat) GetTemperatureCelsius() float32 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

func (x *TapHeartbeat) GetWifiInterface() string {
	if x != nil {
		return x.WifiInterface
	}
	return ""
}

func (x *TapHeartbeat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TapHeartbeat) GetBleInterface() string {
	if x != nil {
		return x.BleInterface
	}
	return ""
}

type TapStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PacketsCaptured    uint64                 `protobuf:"varint,1,opt,name=packets_captured,json=packetsCaptured,proto3" json:"packets_captured,omitempty"`            // Total packets seen
	PacketsFiltered    uint64                 `protobuf:"varint,2,opt,name=packets_filtered,json=packetsFiltered,proto3" json:"packets_filtered,omitempty"`            // Packets passing BPF filter
	DetectionsSent     uint64                 `protobuf:"varint,3,opt,name=detections_sent,json=detectionsSent,proto3" json:"detections_sent,omitempty"`               // Detection messages published
	BytesCaptured      uint64                 `protobuf:"varint,4,opt,name=bytes_captured,json=bytesCaptured,proto3" json:"bytes_captured,omitempty"`                  // Total bytes captured
	CurrentChannel     int32                  `protobuf:"varint,5,opt,name=current_channel,json=currentChannel,proto3" json:"current_channel,omitempty"`               // Current WiFi channel
	PacketsPerSecond   float32                `protobuf:"fixed32,6,opt,name=packets_per_second,json=packetsPerSecond,proto3" json:"packets_per_second,omitempty"`      // Current rate
	UptimeSeconds      uint64                 `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                  // Seconds since tap started
	PcapKernelReceived uint32                 `protobuf:"varint,8,opt,name=pcap_kernel_received,json=pcapKernelReceived,proto3" json:"pcap_kernel_received,omitempty"` // Packets received by kernel
	PcapKernelDropped  uint32                 `protobuf:"varint,9,opt,name=pcap_kernel_dropped,json=pcapKernelDropped,proto3" json:"pcap_kernel_dropped,omitempty"`    // Packets dropped by kernel
	// ── Buffer metrics (reliable delivery) ──
	BufferSize      uint64 `protobuf:"varint,10,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`                // Current buffered detections awaiting publish
	BufferDropped   uint64 `protobuf:"varint,11,opt,name=buffer_dropped,json=bufferDropped,proto3" json:"buffer_dropped,omitempty"`       // Detections dropped due to buffer overflow
	PublishRetries  uint64 `protobuf:"varint,12,opt,name=publish_retries,json=publishRetries,proto3" json:"publish_retries,omitempty"`    // Total publish retry attempts
	NatsDisconnects uint64 `protobuf:"varint,13,opt,name=nats_disconnects,json=natsDisconnects,proto3" json:"nats_disconnects,omitempty"` // NATS disconnection events
	NatsReconnects  uint64 `protobuf:"varint,14,opt,name=nats_reconnects,json=natsReconnects,proto3" json:"nats_reconnects,omitempty"`    // NATS reconnection events
	// ── BSSID baseline metrics ──
	TotalBssids       uint64 `protobuf:"varint,20,opt,name=total_bssids,json=totalBssids,proto3" json:"total_bssids,omitempty"`                     // Total unique BSSIDs ever seen
	NewBssidsInterval uint64 `protobuf:"varint,21,opt,name=new_bssids_interval,json=newBssidsInterval,proto3" json:"new_bssids_interval,omitempty"` // New BSSIDs discovered since last heartbeat
	// ── Channel diversity metrics ──
	DistinctChannels uint32 `protobuf:"varint,22,opt,name=distinct_channels,json=distinctChannels,proto3" json:"distinct_channels,omitempty"` // Distinct frequencies observed in last interval
	// ── tshark co-process metrics ──
	TsharkLines      uint64 `protobuf:"varint,30,opt,name=tshark_lines,json=tsharkLines,proto3" json:"tshark_lines,omitempty"`                // Lines parsed from tshark JSON
	TsharkDetections uint64 `protobuf:"varint,31,opt,name=tshark_detections,json=tsharkDetections,proto3" json:"tshark_detections,omitempty"` // Detections generated from tshark
	TsharkRestarts   uint32 `protobuf:"varint,32,opt,name=tshark_restarts,json=tsharkRestarts,proto3" json:"tshark_restarts,omitempty"`       // tshark process restart count
	// ── BLE scanner metrics ──
	BleAdvertisements uint64 `protobuf:"varint,40,opt,name=ble_advertisements,json=bleAdvertisements,proto3" json:"ble_advertisements,omitempty"` // Total BLE adverts with UUID 0xFFFA seen
	BleDetections     uint64 `protobuf:"varint,41,opt,name=ble_detections,json=bleDetections,proto3" json:"ble_detections,omitempty"`             // Detections generated from BLE
	BleScanning       bool   `protobuf:"varint,42,opt,name=ble_scanning,json=bleScanning,proto3" json:"ble_scanning,omitempty"`                   // Whether BLE scanner is actively running
	BleInterface      string `protobuf:"bytes,43,opt,name=ble_interface,json=bleInterface,proto3" json:"ble_interface,omitempty"`                 // BLE adapter name (e.g., "hci0")
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TapStats) Reset() {
	*x = TapStats{}
	mi := &file_proto_skylens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapStats) ProtoMessage() {}

func (x *TapStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapStats.ProtoReflect.Descriptor instead.
func (*TapStats) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{2}
}

func (x *TapStats) GetPacketsCaptured() uint64 {
	if x != nil {
		return x.PacketsCaptured
	}
	return 0
}

func (x *TapStats) GetPacketsFiltered() uint64 {
	if x != nil {
		return x.PacketsFiltered
	}
	return 0
}

func (x *TapStats) GetDetectionsSent() uint64 {
	if x != nil {
		return x.DetectionsSent
	}
	return 0
}

func (x *TapStats) GetBytesCaptured() uint64 {
	if x != nil {
		return x.BytesCaptured
	}
	return 0
}

func (x *TapStats) GetCurrentChannel() int32 {
	if x != nil {
		return x.CurrentChannel
	}
	return 0
}

func (x *TapStats) GetPacketsPerSecond() float32 {
	if x != nil {
		return x.PacketsPerSecond
	}
	return 0
}

func (x *TapStats) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *TapStats) GetPcapKernelReceived() uint32 {
	if x != nil {
		return x.PcapKernelReceived
	}
	return 0
}

func (x *TapStats) GetPcapKernelDropped() uint32 {
	if x != nil {
		return x.PcapKernelDropped
	}
	return 0
}

func (x *TapStats) GetBufferSize() uint64 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *TapStats) GetBufferDropped() uint64 {
	if x != nil {
		return x.BufferDropped
	}
	return 0
}

func (x *TapStats) GetPublishRetries() uint64 {
	if x != nil {
		return x.PublishRetries
	}
	return 0
}

func (x *TapStats) GetNatsDisconnects() uint64 {
	if x != nil {
		return x.NatsDisconnects
	}
	return 0
}

func (x *TapStats) GetNatsReconnects() uint64 {
	if x != nil {
		return x.NatsReconnects
	}
	return 0
}

func (x *TapStats) GetTotalBssids() uint64 {
	if x != nil {
		return x.TotalBssids
	}
	return 0
}

func (x *TapStats) GetNewBssidsInterval() uint64 {
	if x != nil {
		return x.NewBssidsInterval
	}
	return 0
}

func (x *TapStats) GetDistinctChannels() uint32 {
	if x != nil {
		return x.DistinctChannels
	}
	return 0
}

func (x *TapStats) GetTsharkLines() uint64 {
	if x != nil {
		return x.TsharkLines
	}
	return 0
}

func (x *TapStats) GetTsharkDetections() uint64 {
	if x != nil {
		return x.TsharkDetections
	}
	return 0
}

func (x *TapStats) GetTsharkRestarts() uint32 {
	if x != nil {
		return x.TsharkRestarts
	}
	return 0
}

func (x *TapStats) GetBleAdvertisements() uint64 {
	if x != nil {
		return x.BleAdvertisements
	}
	return 0
}

func (x *TapStats) GetBleDetections() uint64 {
	if x != nil {
		return x.BleDetections
	}
	return 0
}

func (x *TapStats) GetBleScanning() bool {
	if x != nil {
		return x.BleScanning
	}
	return false
}

func (x *TapStats) GetBleInterface() string {
	if x != nil {
		return x.BleInterface
	}
	return ""
}

type TapCommand struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TapId       string                 `protobuf:"bytes,1,opt,name=tap_id,json=tapId,proto3" json:"tap_id,omitempty"` // Target tap (or "*" for broadcast)
	TimestampNs int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	CommandId   string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // For ack tracking
	// Types that are valid to be assigned to Command:
	//
	//	*TapCommand_SetChannels
	//	*TapCommand_SetFilter
	//	*TapCommand_Restart
	//	*TapCommand_UpdateConfig
	//	*TapCommand_Ping
	Command       isTapCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TapCommand) Reset() {
	*x = TapCommand{}
	mi := &file_proto_skylens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapCommand) ProtoMessage() {}

func (x *TapCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapCommand.ProtoReflect.Descriptor instead.
func (*TapCommand) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{3}
}

func (x *TapCommand) GetTapId() string {
	if x != nil {
		return x.TapId
	}
	return ""
}

func (x *TapCommand) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TapCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TapCommand) GetCommand() isTapCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TapCommand) GetSetChannels() *SetChannelsCommand {
	if x != nil {
		if x, ok := x.Command.(*TapCommand_SetChannels); ok {
			return x.SetChannels
		}
	}
	return nil
}

func (x *TapCommand) GetSetFilter() *SetFilterCommand {
	if x != nil {
		if x, ok := x.Command.(*TapCommand_SetFilter); ok {
			return x.SetFilter
		}
	}
	return nil
}

func (x *TapCommand) GetRestart() *RestartCommand {
	if x != nil {
		if x, ok := x.Command.(*TapCommand_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *TapCommand) GetUpdateConfig() *UpdateConfigCommand {
	if x != nil {
		if x, ok := x.Command.(*TapCommand_UpdateConfig); ok {
			return x.UpdateConfig
		}
	}
	return nil
}

func (x *TapCommand) GetPing() *PingCommand {
	if x != nil {
		if x, ok := x.Command.(*TapCommand_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isTapCommand_Command interface {
	isTapCommand_Command()
}

type TapCommand_SetChannels struct {
	SetChannels *SetChannelsCommand `protobuf:"bytes,10,opt,name=set_channels,json=setChannels,proto3,oneof"`
}

type TapCommand_SetFilter struct {
	SetFilter *SetFilterCommand `protobuf:"bytes,11,opt,name=set_filter,json=setFilter,proto3,oneof"`
}

type TapCommand_Restart struct {
	Restart *RestartCommand `protobuf:"bytes,12,opt,name=restart,proto3,oneof"`
}

type TapCommand_UpdateConfig struct {
	UpdateConfig *UpdateConfigCommand `protobuf:"bytes,13,opt,name=update_config,json=updateConfig,proto3,oneof"`
}

type TapCommand_Ping struct {
	Ping *PingCommand `protobuf:"bytes,14,opt,name=ping,proto3,oneof"`
}

func (*TapCommand_SetChannels) isTapCommand_Command() {}

func (*TapCommand_SetFilter) isTapCommand_Command() {}

func (*TapCommand_Restart) isTapCommand_Command() {}

func (*TapCommand_UpdateConfig) isTapCommand_Command() {}

func (*TapCommand_Ping) isTapCommand_Command() {}

type SetChannelsCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []int32                `protobuf:"varint,1,rep,packed,name=channels,proto3" json:"channels,omitempty"`                           // Channels to hop between
	HopIntervalMs int32                  `protobuf:"varint,2,opt,name=hop_interval_ms,json=hopIntervalMs,proto3" json:"hop_interval_ms,omitempty"` // Dwell time per channel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetChannelsCommand) Reset() {
	*x = SetChannelsCommand{}
	mi := &file_proto_skylens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetChannelsCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChannelsCommand) ProtoMessage() {}

func (x *SetChannelsCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChannelsCommand.ProtoReflect.Descriptor instead.
func (*SetChannelsCommand) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{4}
}

func (x *SetChannelsCommand) GetChannels() []int32 {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *SetChannelsCommand) GetHopIntervalMs() int32 {
	if x != nil {
		return x.HopIntervalMs
	}
	return 0
}

type SetFilterCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BpfFilter     string                 `protobuf:"bytes,1,opt,name=bpf_filter,json=bpfFilter,proto3" json:"bpf_filter,omitempty"` // New BPF filter expression
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFilterCommand) Reset() {
	*x = SetFilterCommand{}
	mi := &file_proto_skylens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFilterCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFilterCommand) ProtoMessage() {}

func (x *SetFilterCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFilterCommand.ProtoReflect.Descriptor instead.
func (*SetFilterCommand) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{5}
}

func (x *SetFilterCommand) GetBpfFilter() string {
	if x != nil {
		return x.BpfFilter
	}
	return ""
}

type RestartCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graceful      bool                   `protobuf:"varint,1,opt,name=graceful,proto3" json:"graceful,omitempty"` // Wait for in-flight packets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartCommand) Reset() {
	*x = RestartCommand{}
	mi := &file_proto_skylens_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartCommand) ProtoMessage() {}

func (x *RestartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartCommand.ProtoReflect.Descriptor instead.
func (*RestartCommand) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{6}
}

func (x *RestartCommand) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type UpdateConfigCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value config updates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigCommand) Reset() {
	*x = UpdateConfigCommand{}
	mi := &file_proto_skylens_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigCommand) ProtoMessage() {}

func (x *UpdateConfigCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigCommand.ProtoReflect.Descriptor instead.
func (*UpdateConfigCommand) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateConfigCommand) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type PingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAtNs      int64                  `protobuf:"varint,1,opt,name=sent_at_ns,json=sentAtNs,proto3" json:"sent_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCommand) Reset() {
	*x = PingCommand{}
	mi := &file_proto_skylens_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCommand) ProtoMessage() {}

func (x *PingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCommand.ProtoReflect.Descriptor instead.
func (*PingCommand) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{8}
}

func (x *PingCommand) GetSentAtNs() int64 {
	if x != nil {
		return x.SentAtNs
	}
	return 0
}

type TapCommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TapId         string                 `protobuf:"bytes,1,opt,name=tap_id,json=tapId,proto3" json:"tap_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LatencyNs     int64                  `protobuf:"varint,5,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"` // For ping responses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TapCommandAck) Reset() {
	*x = TapCommandAck{}
	mi := &file_proto_skylens_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapCommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapCommandAck) ProtoMessage() {}

func (x *TapCommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapCommandAck.ProtoReflect.Descriptor instead.
func (*TapCommandAck) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{9}
}

func (x *TapCommandAck) GetTapId() string {
	if x != nil {
		return x.TapId
	}
	return ""
}

func (x *TapCommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TapCommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TapCommandAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TapCommandAck) GetLatencyNs() int64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

type Alert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AlertId         string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	TimestampNs     int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Priority        AlertPriority          `protobuf:"varint,3,opt,name=priority,proto3,enum=skylens.AlertPriority" json:"priority,omitempty"`
	AlertType       AlertType              `protobuf:"varint,4,opt,name=alert_type,json=alertType,proto3,enum=skylens.AlertType" json:"alert_type,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Message         string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	DroneIdentifier string                 `protobuf:"bytes,7,opt,name=drone_identifier,json=droneIdentifier,proto3" json:"drone_identifier,omitempty"` // Related drone if applicable
	TapId           string                 `protobuf:"bytes,8,opt,name=tap_id,json=tapId,proto3" json:"tap_id,omitempty"`                               // Source tap if applicable
	Metadata        map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_skylens_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skylens_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_skylens_proto_rawDescGZIP(), []int{10}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Alert) GetPriority() AlertPriority {
	if x != nil {
		return x.Priority
	}
	return AlertPriority_ALERT_INFO
}

func (x *Alert) GetAlertType() AlertType {
	if x != nil {
		return x.AlertType
	}
	return AlertType_ALERT_TYPE_UNKNOWN
}

func (x *Alert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetDroneIdentifier() string {
	if x != nil {
		return x.DroneIdentifier
	}
	return ""
}

func (x *Alert) GetTapId() string {
	if x != nil {
		return x.TapId
	}
	return ""
}

func (x *Alert) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_skylens_proto protoreflect.FileDescriptor

const file_proto_skylens_proto_rawDesc = "" +
	"\n" +
	"\x13proto/skylens.proto\x12\askylens\"\x81\f\n" +
	"\tDetection\x12\x15\n" +
	"\x06tap_id\x18\x01 \x01(\tR\x05tapId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x1e\n" +
	"\n" +
	"identifier\x18\x04 \x01(\tR\n" +
	"identifier\x12#\n" +
	"\rserial_number\x18\x05 \x01(\tR\fserialNumber\x12\"\n" +
	"\fregistration\x18\x06 \x01(\tR\fregistration\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12\x15\n" +
	"\x06utm_id\x18\b \x01(\tR\x05utmId\x12\x1a\n" +
	"\blatitude\x18\n" +
	" \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\v \x01(\x01R\tlongitude\x12+\n" +
	"\x11altitude_geodetic\x18\f \x01(\x02R\x10altitudeGeodetic\x12+\n" +
	"\x11altitude_pressure\x18\r \x01(\x02R\x10altitudePressure\x12\x1d\n" +
	"\n" +
	"height_agl\x18\x0e \x01(\x02R\theightAgl\x12C\n" +
	"\x10height_reference\x18\x0f \x01(\x0e2\x18.skylens.HeightReferenceR\x0fheightReference\x12\x14\n" +
	"\x05speed\x18\x14 \x01(\x02R\x05speed\x12%\n" +
	"\x0evertical_speed\x18\x15 \x01(\x02R\rverticalSpeed\x12\x18\n" +
	"\aheading\x18\x16 \x01(\x02R\aheading\x12'\n" +
	"\x0ftrack_direction\x18\x17 \x01(\x02R\x0etrackDirection\x12+\n" +
	"\x11operator_latitude\x18\x1e \x01(\x01R\x10operatorLatitude\x12-\n" +
	"\x12operator_longitude\x18\x1f \x01(\x01R\x11operatorLongitude\x12+\n" +
	"\x11operator_altitude\x18  \x01(\x02R\x10operatorAltitude\x12S\n" +
	"\x16operator_location_type\x18! \x01(\x0e2\x1d.skylens.OperatorLocationTypeR\x14operatorLocationType\x12\x1f\n" +
	"\voperator_id\x18\" \x01(\tR\n" +
	"operatorId\x12\x12\n" +
	"\x04rssi\x18( \x01(\x05R\x04rssi\x12\x18\n" +
	"\achannel\x18) \x01(\x05R\achannel\x12#\n" +
	"\rfrequency_mhz\x18* \x01(\x05R\ffrequencyMhz\x12\x12\n" +
	"\x04ssid\x18+ \x01(\tR\x04ssid\x12,\n" +
	"\x12beacon_interval_tu\x18, \x01(\rR\x10beaconIntervalTu\x120\n" +
	"\x06source\x182 \x01(\x0e2\x18.skylens.DetectionSourceR\x06source\x12\x19\n" +
	"\buav_type\x183 \x01(\tR\auavType\x127\n" +
	"\fuav_category\x184 \x01(\x0e2\x14.skylens.UAVCategoryR\vuavCategory\x12 \n" +
	"\vdesignation\x185 \x01(\tR\vdesignation\x12\"\n" +
	"\fmanufacturer\x186 \x01(\tR\fmanufacturer\x12I\n" +
	"\x12operational_status\x187 \x01(\x0e2\x1a.skylens.OperationalStatusR\x11operationalStatus\x12\x1e\n" +
	"\n" +
	"confidence\x188 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\ris_controller\x18: \x01(\bR\fisController\x12!\n" +
	"\fcountry_code\x18; \x01(\tR\vcountryCode\x12\x1b\n" +
	"\traw_frame\x18< \x01(\fR\brawFrame\x12)\n" +
	"\x10remoteid_payload\x18= \x01(\fR\x0fremoteidPayload\x12'\n" +
	"\x0fht_capabilities\x18F \x01(\rR\x0ehtCapabilities\"\xc1\x03\n" +
	"\fTapHeartbeat\x12\x15\n" +
	"\x06tap_id\x18\x01 \x01(\tR\x05tapId\x12\x19\n" +
	"\btap_name\x18\x02 \x01(\tR\atapName\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x12\x1a\n" +
	"\blatitude\x18\n" +
	" \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\v \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\f \x01(\x02R\baltitude\x12'\n" +
	"\x05stats\x18\x14 \x01(\v2\x11.skylens.TapStatsR\x05stats\x12\x1f\n" +
	"\vcpu_percent\x18\x1e \x01(\x02R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x1f \x01(\x02R\rmemoryPercent\x12/\n" +
	"\x13temperature_celsius\x18  \x01(\x02R\x12temperatureCelsius\x12%\n" +
	"\x0ewifi_interface\x18! \x01(\tR\rwifiInterface\x12\x18\n" +
	"\aversion\x18\" \x01(\tR\aversion\x12#\n" +
	"\rble_interface\x18# \x01(\tR\fbleInterface\"\xec\a\n" +
	"\bTapStats\x12)\n" +
	"\x10packets_captured\x18\x01 \x01(\x04R\x0fpacketsCaptured\x12)\n" +
	"\x10packets_filtered\x18\x02 \x01(\x04R\x0fpacketsFiltered\x12'\n" +
	"\x0fdetections_sent\x18\x03 \x01(\x04R\x0edetectionsSent\x12%\n" +
	"\x0ebytes_captured\x18\x04 \x01(\x04R\rbytesCaptured\x12'\n" +
	"\x0fcurrent_channel\x18\x05 \x01(\x05R\x0ecurrentChannel\x12,\n" +
	"\x12packets_per_second\x18\x06 \x01(\x02R\x10packetsPerSecond\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x04R\ruptimeSeconds\x120\n" +
	"\x14pcap_kernel_received\x18\b \x01(\rR\x12pcapKernelReceived\x12.\n" +
	"\x13pcap_kernel_dropped\x18\t \x01(\rR\x11pcapKernelDropped\x12\x1f\n" +
	"\vbuffer_size\x18\n" +
	" \x01(\x04R\n" +
	"bufferSize\x12%\n" +
	"\x0ebuffer_dropped\x18\v \x01(\x04R\rbufferDropped\x12'\n" +
	"\x0fpublish_retries\x18\f \x01(\x04R\x0epublishRetries\x12)\n" +
	"\x10nats_disconnects\x18\r \x01(\x04R\x0fnatsDisconnects\x12'\n" +
	"\x0fnats_reconnects\x18\x0e \x01(\x04R\x0enatsReconnects\x12!\n" +
	"\ftotal_bssids\x18\x14 \x01(\x04R\vtotalBssids\x12.\n" +
	"\x13new_bssids_interval\x18\x15 \x01(\x04R\x11newBssidsInterval\x12+\n" +
	"\x11distinct_channels\x18\x16 \x01(\rR\x10distinctChannels\x12!\n" +
	"\ftshark_lines\x18\x1e \x01(\x04R\vtsharkLines\x12+\n" +
	"\x11tshark_detections\x18\x1f \x01(\x04R\x10tsharkDetections\x12'\n" +
	"\x0ftshark_restarts\x18  \x01(\rR\x0etsharkRestarts\x12-\n" +
	"\x12ble_advertisements\x18( \x01(\x04R\x11bleAdvertisements\x12%\n" +
	"\x0eble_detections\x18) \x01(\x04R\rbleDetections\x12!\n" +
	"\fble_scanning\x18* \x01(\bR\vbleScanning\x12#\n" +
	"\rble_interface\x18+ \x01(\tR\fbleInterface\"\x94\x03\n" +
	"\n" +
	"TapCommand\x12\x15\n" +
	"\x06tap_id\x18\x01 \x01(\tR\x05tapId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12@\n" +
	"\fset_channels\x18\n" +
	" \x01(\v2\x1b.skylens.SetChannelsCommandH\x00R\vsetChannels\x12:\n" +
	"\n" +
	"set_filter\x18\v \x01(\v2\x19.skylens.SetFilterCommandH\x00R\tsetFilter\x123\n" +
	"\arestart\x18\f \x01(\v2\x17.skylens.RestartCommandH\x00R\arestart\x12C\n" +
	"\rupdate_config\x18\r \x01(\v2\x1c.skylens.UpdateConfigCommandH\x00R\fupdateConfig\x12*\n" +
	"\x04ping\x18\x0e \x01(\v2\x14.skylens.PingCommandH\x00R\x04pingB\t\n" +
	"\acommand\"X\n" +
	"\x12SetChannelsCommand\x12\x1a\n" +
	"\bchannels\x18\x01 \x03(\x05R\bchannels\x12&\n" +
	"\x0fhop_interval_ms\x18\x02 \x01(\x05R\rhopIntervalMs\"1\n" +
	"\x10SetFilterCommand\x12\x1d\n" +
	"\n" +
	"bpf_filter\x18\x01 \x01(\tR\tbpfFilter\",\n" +
	"\x0eRestartCommand\x12\x1a\n" +
	"\bgraceful\x18\x01 \x01(\bR\bgraceful\"\x92\x01\n" +
	"\x13UpdateConfigCommand\x12@\n" +
	"\x06config\x18\x01 \x03(\v2(.skylens.UpdateConfigCommand.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\vPingCommand\x12\x1c\n" +
	"\n" +
	"sent_at_ns\x18\x01 \x01(\x03R\bsentAtNs\"\xa3\x01\n" +
	"\rTapCommandAck\x12\x15\n" +
	"\x06tap_id\x18\x01 \x01(\tR\x05tapId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\x05 \x01(\x03R\tlatencyNs\"\x95\x03\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x122\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x16.skylens.AlertPriorityR\bpriority\x121\n" +
	"\n" +
	"alert_type\x18\x04 \x01(\x0e2\x12.skylens.AlertTypeR\talertType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12)\n" +
	"\x10drone_identifier\x18\a \x01(\tR\x0fdroneIdentifier\x12\x15\n" +
	"\x06tap_id\x18\b \x01(\tR\x05tapId\x128\n" +
	"\bmetadata\x18\t \x03(\v2\x1c.skylens.Alert.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xfc\x01\n" +
	"\x0fDetectionSource\x12\x12\n" +
	"\x0eSOURCE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12SOURCE_WIFI_BEACON\x10\x01\x12\x13\n" +
	"\x0fSOURCE_WIFI_NAN\x10\x02\x12\x1a\n" +
	"\x16SOURCE_WIFI_PROBE_RESP\x10\x03\x12\x16\n" +
	"\x12SOURCE_BLUETOOTH_4\x10\x04\x12\x16\n" +
	"\x12SOURCE_BLUETOOTH_5\x10\x05\x12\x16\n" +
	"\x12SOURCE_DJI_OCUSYNC\x10\x06\x12\x10\n" +
	"\fSOURCE_ADS_B\x10\a\x12\x1a\n" +
	"\x16SOURCE_TSHARK_REMOTEID\x10\b\x12\x16\n" +
	"\x12SOURCE_TSHARK_SSID\x10\t*X\n" +
	"\x0fHeightReference\x12\x16\n" +
	"\x12HEIGHT_REF_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12HEIGHT_REF_TAKEOFF\x10\x01\x12\x15\n" +
	"\x11HEIGHT_REF_GROUND\x10\x02*f\n" +
	"\x14OperatorLocationType\x12\x12\n" +
	"\x0eOP_LOC_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eOP_LOC_TAKEOFF\x10\x01\x12\x14\n" +
	"\x10OP_LOC_LIVE_GNSS\x10\x02\x12\x10\n" +
	"\fOP_LOC_FIXED\x10\x03*\xff\x02\n" +
	"\vUAVCategory\x12\x13\n" +
	"\x0fUAV_CAT_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12UAV_CAT_UNDECLARED\x10\x01\x12\x15\n" +
	"\x11UAV_CAT_AEROPLANE\x10\x02\x12\x16\n" +
	"\x12UAV_CAT_HELICOPTER\x10\x03\x12\x15\n" +
	"\x11UAV_CAT_GYROPLANE\x10\x04\x12\x17\n" +
	"\x13UAV_CAT_HYBRID_LIFT\x10\x05\x12\x17\n" +
	"\x13UAV_CAT_ORNITHOPTER\x10\x06\x12\x12\n" +
	"\x0eUAV_CAT_GLIDER\x10\a\x12\x10\n" +
	"\fUAV_CAT_KITE\x10\b\x12\x18\n" +
	"\x14UAV_CAT_FREE_BALLOON\x10\t\x12\x1b\n" +
	"\x17UAV_CAT_CAPTIVE_BALLOON\x10\n" +
	"\x12\x13\n" +
	"\x0fUAV_CAT_AIRSHIP\x10\v\x12\x15\n" +
	"\x11UAV_CAT_FREE_FALL\x10\f\x12\x12\n" +
	"\x0eUAV_CAT_ROCKET\x10\r\x12\x1b\n" +
	"\x17UAV_CAT_GROUND_OBSTACLE\x10\x0e\x12\x11\n" +
	"\rUAV_CAT_OTHER\x10\x0f*\xac\x01\n" +
	"\x11OperationalStatus\x12\x15\n" +
	"\x11OP_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14OP_STATUS_UNDECLARED\x10\x01\x12\x14\n" +
	"\x10OP_STATUS_GROUND\x10\x02\x12\x16\n" +
	"\x12OP_STATUS_AIRBORNE\x10\x03\x12\x17\n" +
	"\x13OP_STATUS_EMERGENCY\x10\x04\x12\x1f\n" +
	"\x1bOP_STATUS_REMOTE_ID_FAILURE\x10\x05*V\n" +
	"\rAlertPriority\x12\x0e\n" +
	"\n" +
	"ALERT_INFO\x10\x00\x12\x11\n" +
	"\rALERT_WARNING\x10\x01\x12\x0e\n" +
	"\n" +
	"ALERT_HIGH\x10\x02\x12\x12\n" +
	"\x0eALERT_CRITICAL\x10\x03*\x84\x02\n" +
	"\tAlertType\x12\x16\n" +
	"\x12ALERT_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ALERT_TYPE_NEW_DRONE\x10\x01\x12\x19\n" +
	"\x15ALERT_TYPE_DRONE_LOST\x10\x02\x12\x1d\n" +
	"\x19ALERT_TYPE_SPOOF_DETECTED\x10\x03\x12\x1d\n" +
	"\x19ALERT_TYPE_ZONE_VIOLATION\x10\x04\x12\x18\n" +
	"\x14ALERT_TYPE_LOW_TRUST\x10\x05\x12\x1a\n" +
	"\x16ALERT_TYPE_TAP_OFFLINE\x10\x06\x12\x19\n" +
	"\x15ALERT_TYPE_TAP_ONLINE\x10\a\x12\x1b\n" +
	"\x17ALERT_TYPE_SYSTEM_ERROR\x10\bB'Z%github.com/skylens/skylens-node/protob\x06proto3"

var (
	file_proto_skylens_proto_rawDescOnce sync.Once
	file_proto_skylens_proto_rawDescData []byte
)

func file_proto_skylens_proto_rawDescGZIP() []byte {
	file_proto_skylens_proto_rawDescOnce.Do(func() {
		file_proto_skylens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_skylens_proto_rawDesc), len(file_proto_skylens_proto_rawDesc)))
	})
	return file_proto_skylens_proto_rawDescData
}

var file_proto_skylens_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_proto_skylens_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_skylens_proto_goTypes = []any{
	(DetectionSource)(0),        // 0: skylens.DetectionSource
	(HeightReference)(0),        // 1: skylens.HeightReference
	(OperatorLocationType)(0),   // 2: skylens.OperatorLocationType
	(UAVCategory)(0),            // 3: skylens.UAVCategory
	(OperationalStatus)(0),      // 4: skylens.OperationalStatus
	(AlertPriority)(0),          // 5: skylens.AlertPriority
	(AlertType)(0),              // 6: skylens.AlertType
	(*Detection)(nil),           // 7: skylens.Detection
	(*TapHeartbeat)(nil),        // 8: skylens.TapHeartbeat
	(*TapStats)(nil),            // 9: skylens.TapStats
	(*TapCommand)(nil),          // 10: skylens.TapCommand
	(*SetChannelsCommand)(nil),  // 11: skylens.SetChannelsCommand
	(*SetFilterCommand)(nil),    // 12: skylens.SetFilterCommand
	(*RestartCommand)(nil),      // 13: skylens.RestartCommand
	(*UpdateConfigCommand)(nil), // 14: skylens.UpdateConfigCommand
	(*PingCommand)(nil),         // 15: skylens.PingCommand
	(*TapCommandAck)(nil),       // 16: skylens.TapCommandAck
	(*Alert)(nil),               // 17: skylens.Alert
	nil,                         // 18: skylens.UpdateConfigCommand.ConfigEntry
	nil,                         // 19: skylens.Alert.MetadataEntry
}
var file_proto_skylens_proto_depIdxs = []int32{
	1,  // 0: skylens.Detection.height_reference:type_name -> skylens.HeightReference
	2,  // 1: skylens.Detection.operator_location_type:type_name -> skylens.OperatorLocationType
	0,  // 2: skylens.Detection.source:type_name -> skylens.DetectionSource
	3,  // 3: skylens.Detection.uav_category:type_name -> skylens.UAVCategory
	4,  // 4: skylens.Detection.operational_status:type_name -> skylens.OperationalStatus
	9,  // 5: skylens.TapHeartbeat.stats:type_name -> skylens.TapStats
	11, // 6: skylens.TapCommand.set_channels:type_name -> skylens.SetChannelsCommand
	12, // 7: skylens.TapCommand.set_filter:type_name -> skylens.SetFilterCommand
	13, // 8: skylens.TapCommand.restart:type_name -> skylens.RestartCommand
	14, // 9: skylens.TapCommand.update_config:type_name -> skylens.UpdateConfigCommand
	15, // 10: skylens.TapCommand.ping:type_name -> skylens.PingCommand
	18, // 11: skylens.UpdateConfigCommand.config:type_name -> skylens.UpdateConfigCommand.ConfigEntry
	5,  // 12: skylens.Alert.priority:type_name -> skylens.AlertPriority
	6,  // 13: skylens.Alert.alert_type:type_name -> skylens.AlertType
	19, // 14: skylens.Alert.metadata:type_name -> skylens.Alert.MetadataEntry
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_skylens_proto_init() }
func file_proto_skylens_proto_init() {
	if File_proto_skylens_proto != nil {
		return
	}
	file_proto_skylens_proto_msgTypes[3].OneofWrappers = []any{
		(*TapCommand_SetChannels)(nil),
		(*TapCommand_SetFilter)(nil),
		(*TapCommand_Restart)(nil),
		(*TapCommand_UpdateConfig)(nil),
		(*TapCommand_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_skylens_proto_rawDesc), len(file_proto_skylens_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_skylens_proto_goTypes,
		DependencyIndexes: file_proto_skylens_proto_depIdxs,
		EnumInfos:         file_proto_skylens_proto_enumTypes,
		MessageInfos:      file_proto_skylens_proto_msgTypes,
	}.Build()
	File_proto_skylens_proto = out.File
	file_proto_skylens_proto_goTypes = nil
	file_proto_skylens_proto_depIdxs = nil
}
